# This is a basic workflow to help you get started with Actions
name: unit-test
on: 
  push: 
    branches: ["master"]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - run: flutter test
